"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-07 05:51:40.203676

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=10), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activities_entity",
        "activities",
        ["entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "customers",
        sa.Column("ragione_sociale", sa.String(length=255), nullable=False),
        sa.Column("partita_iva", sa.String(length=11), nullable=True),
        sa.Column("codice_fiscale", sa.String(length=16), nullable=True),
        sa.Column("codice_sdi", sa.String(length=7), nullable=True),
        sa.Column("pec", sa.String(length=320), nullable=True),
        sa.Column("indirizzo", sa.String(length=255), nullable=True),
        sa.Column("cap", sa.String(length=10), nullable=True),
        sa.Column("comune", sa.String(length=120), nullable=True),
        sa.Column("provincia", sa.String(length=2), nullable=True),
        sa.Column("nazione", sa.String(length=2), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("sito_web", sa.String(length=255), nullable=True),
        sa.Column("stato", sa.String(length=40), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_customers_custom_fields",
        "customers",
        ["custom_fields"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_customers_partita_iva"), "customers", ["partita_iva"], unique=False)
    op.create_index("ix_customers_ragione_sociale", "customers", ["ragione_sociale"], unique=False)
    op.create_table(
        "field_definitions",
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("field_type", sa.String(length=20), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "key", name="uq_field_entity_key"),
    )
    op.create_index(
        op.f("ix_field_definitions_archived"), "field_definitions", ["archived"], unique=False
    )
    op.create_index(
        op.f("ix_field_definitions_entity_type"), "field_definitions", ["entity_type"], unique=False
    )
    op.create_table(
        "pipeline_stages",
        sa.Column("nome", sa.String(length=60), nullable=False),
        sa.Column("posizione", sa.Integer(), nullable=False),
        sa.Column("probabilita_default", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=10), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("uq_pipeline_stage_code", "pipeline_stages", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("ruolo", sa.String(length=20), nullable=False),
        sa.Column("attivo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "deals",
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_stage_id", sa.Uuid(), nullable=False),
        sa.Column("valore_previsto", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("probabilita", sa.Integer(), nullable=False),
        sa.Column("data_chiusura_prevista", sa.Date(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("ore_preventivate", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("valore_preventivato", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_stage_id"],
            ["pipeline_stages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deals_custom_fields", "deals", ["custom_fields"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_deals_customer_id"), "deals", ["customer_id"], unique=False)
    op.create_index(
        op.f("ix_deals_pipeline_stage_id"), "deals", ["pipeline_stage_id"], unique=False
    )
    op.create_table(
        "people",
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("cognome", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("ruolo", sa.String(length=120), nullable=True),
        sa.Column("linkedin", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_people_custom_fields", "people", ["custom_fields"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_people_customer_id"), "people", ["customer_id"], unique=False)
    op.create_index(op.f("ix_people_email"), "people", ["email"], unique=False)
    op.create_table(
        "personal_access_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_access_tokens_token_hash"),
        "personal_access_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_personal_access_tokens_user_id"),
        "personal_access_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_personal_access_tokens_user_id"), table_name="personal_access_tokens")
    op.drop_index(op.f("ix_personal_access_tokens_token_hash"), table_name="personal_access_tokens")
    op.drop_table("personal_access_tokens")
    op.drop_index(op.f("ix_people_email"), table_name="people")
    op.drop_index(op.f("ix_people_customer_id"), table_name="people")
    op.drop_index("ix_people_custom_fields", table_name="people", postgresql_using="gin")
    op.drop_table("people")
    op.drop_index(op.f("ix_deals_pipeline_stage_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_customer_id"), table_name="deals")
    op.drop_index("ix_deals_custom_fields", table_name="deals", postgresql_using="gin")
    op.drop_table("deals")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("uq_pipeline_stage_code", table_name="pipeline_stages")
    op.drop_table("pipeline_stages")
    op.drop_index(op.f("ix_field_definitions_entity_type"), table_name="field_definitions")
    op.drop_index(op.f("ix_field_definitions_archived"), table_name="field_definitions")
    op.drop_table("field_definitions")
    op.drop_index("ix_customers_ragione_sociale", table_name="customers")
    op.drop_index(op.f("ix_customers_partita_iva"), table_name="customers")
    op.drop_index("ix_customers_custom_fields", table_name="customers", postgresql_using="gin")
    op.drop_table("customers")
    op.drop_index("ix_activities_entity", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
