"""Queries only. Never commits -- the service owns the transaction.

The in-flight authorisation state is not duplicated here: `google_oauth_states` serves
both the Gmail and the Drive flow (see `GoogleOAuthState.purpose`), and
`GmailRepository.add_state`/`consume_state` already implement the one-statement,
race-safe redemption that a second copy of the same logic could only get wrong by
drifting from it. This repository owns the one table that is Drive's alone.
"""

from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from pigrocrm.core.drive.models import GoogleDriveAccount


class DriveRepository:
    def __init__(self, session: Session) -> None:
        self.session = session

    def account_for_user(self, user_id: UUID) -> GoogleDriveAccount | None:
        return self.session.execute(
            select(GoogleDriveAccount).where(GoogleDriveAccount.user_id == user_id)
        ).scalar_one_or_none()

    def storage_account(self) -> GoogleDriveAccount | None:
        """The account whose credential may write generated documents, or `None`.

        Two conditions, and both are refusals rather than filters. `status == 'active'`:
        a revoked, expired or disconnected grant cannot write, and answering with one
        would turn a fixable settings problem into a Google error three requests deep.
        `storage_folder_id IS NOT NULL`: connected is not configured -- a Drive with no
        chosen folder must never be written into, because the only alternative would be
        picking a folder somewhere in somebody's personal Drive on their behalf.

        No `user_id`, unlike `account_for_user`: this is not somebody's Drive, it is
        *the installation's* place to put documents. A document generated by an
        automation, or uploaded by a collaborator who has no Google account of their
        own, is written with the titolare's credential -- so the question this answers
        has no actor in it.

        `scalar_one_or_none` is deliberately not used, and `LIMIT 1` is not a
        micro-optimisation. The installation is single-tenant and `user_id` is unique,
        so more than one qualifying row is not the expected state -- but it is reachable
        (two users each connect a Drive and each choose a folder), and a query that
        raised `MultipleResultsFound` there would take every upload and every download
        down with it. The most recently updated row is the answer instead: it is the one
        somebody most recently chose.
        """
        return self.session.execute(
            select(GoogleDriveAccount)
            .where(
                GoogleDriveAccount.status == "active",
                GoogleDriveAccount.storage_folder_id.is_not(None),
            )
            .order_by(GoogleDriveAccount.updated_at.desc())
            .limit(1)
        ).scalar_one_or_none()

    def add(self, account: GoogleDriveAccount) -> GoogleDriveAccount:
        self.session.add(account)
        self.session.flush()
        return account
