"""documents templates emitter

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-20 21:13:00.079840

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emitter_profile",
        sa.Column("singleton", sa.Boolean(), nullable=False),
        sa.Column("ragione_sociale", sa.String(length=255), nullable=False),
        sa.Column("partita_iva", sa.String(length=11), nullable=True),
        sa.Column("codice_fiscale", sa.String(length=16), nullable=True),
        sa.Column("indirizzo", sa.String(length=255), nullable=True),
        sa.Column("cap", sa.String(length=10), nullable=True),
        sa.Column("comune", sa.String(length=120), nullable=True),
        sa.Column("provincia", sa.String(length=2), nullable=True),
        sa.Column("nazione", sa.String(length=2), nullable=False),
        sa.Column("pec", sa.String(length=320), nullable=True),
        sa.Column("codice_sdi", sa.String(length=7), nullable=True),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("sito_web", sa.String(length=255), nullable=True),
        sa.Column("logo_key", sa.String(length=255), nullable=True),
        sa.Column("firma_key", sa.String(length=255), nullable=True),
        sa.Column("regime_fiscale", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("singleton"),
    )
    op.create_table(
        "templates",
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("corpo_markdown", sa.Text(), nullable=False),
        sa.Column("variabili_dichiarate", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attivo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_templates_nome", "templates", [sa.literal_column("lower(nome)")], unique=True
    )
    op.create_table(
        "documents",
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("titolo", sa.String(length=200), nullable=False),
        sa.Column("stato", sa.String(length=20), nullable=True),
        sa.Column("versione_corrente", sa.Integer(), nullable=False),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(customer_id IS NOT NULL) <> (deal_id IS NOT NULL)",
            name="ck_documents_customer_xor_deal",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_documents_custom_fields",
        "documents",
        ["custom_fields"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_documents_customer_id"), "documents", ["customer_id"], unique=False)
    op.create_index(op.f("ix_documents_deal_id"), "documents", ["deal_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("sorgente_markdown", sa.Text(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("variabili", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("dimensione", sa.Integer(), nullable=False),
        sa.Column("hash_sha256", sa.String(length=64), nullable=False),
        sa.Column("creato_da", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creato_da"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "numero", name="uq_document_versions_document_numero"),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_deal_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_customer_id"), table_name="documents")
    op.drop_index("ix_documents_custom_fields", table_name="documents", postgresql_using="gin")
    op.drop_table("documents")
    op.drop_index("uq_templates_nome", table_name="templates")
    op.drop_table("templates")
    op.drop_table("emitter_profile")
    # ### end Alembic commands ###
